### ISSUE TITLE
Find next zodiac change for an object

### ISSUE THREAD

**Issue by Ptitematil2** [astrorigin/swephelp#1]
I'm looking to know when an object change zodiac sign, is there already a way to do it ? Or maybe it can be a new feature ?

**Comment by astrorigin** [comment]
It is possible.

If you are using pyswisseph:

It is easier when using function swisseph.contrib.next_aspect(...)
That function was very recently renamed and previously was in private: swisseph._next_aspect

In any case we advise you to try the development version, because drastic changes were made.

If you are using swephelp (in C): please read documentation.

**Comment by astrorigin** [comment]
In fact we're going to make a dedicated function for that. Thanks for your question.

**Comment by astrorigin** [comment]
Problem solved
